export const data = [
  // Livermore
  {
    img: "http://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41072444/0/0/0/e9a807118753bb7a1b4073077d34ce65/136/a3d8195609b4d50c937704c382b57814/41072444-ba403fce-bfd0-4954-b9e3-d4180edb29a4.JPG",
    price: 1599000,
    area: 2152,
    beds: 4,
    baths: 3,
    location: "livermore",
    type: "residential",
    built: 1973,
    address: "2332 Chateau Way Livermore CA, 94550",
    interior: [
      {
        stories: 1,
        bedrooms: 4,
        totalBathrooms: 3,
        fullBathrooms: 2,
        interiorFeatures: [
          "Den",
          "Family Room",
          "Library",
          "Office",
          "Breakfast Bar",
          "Breakfast Nook",
          "Stone Counters",
          "Eat in Kitchen",
          "Updated Kitchen",
        ],
        appliances: [
          "Dishwasher",
          "Disposal",
          "Microwave",
          "Oven",
          "Refrigerator",
          "Dryer",
          "Washer",
          "Electric Water Heater",
        ],
        laundryDescription: "in garage",
        floorDescription: "Hardwood Flrs Throughout",
        fireplace: true,
        fireplaceDescription: "living room",
        cooling: true,
        coolingDescription: "central air",
        heating: true,
        heatingDescription: "forced air",
      },
    ],
    exterior: [
      {
        lotSize: 0.21,
        exteriorFeatures: [
          "Back Yard",
          "Dog Run",
          "Front Yard",
          "Garden/Play",
          "Side Yard",
        ],
        lotFeatures: ["level", "premium lot"],
        architechturalStyle: "ranch",
        roof: "shingle",
        sewer: "public sewer",
      },
    ],
    schoolInformation: [{ schoolDistrict: "Livermore Valley (925) 606-3200" }],
    otherDetails: [
      {
        garage: true,
        garageSpaces: 2,
        parking: ["Attached", " RV/Boat Parking", "Side Yard Access"],
        parkingTotal: 2,
        view: false,
        county: "alameda",
        waterSource: "public",
        pool: true,
        poolFeatures: ["In Ground", "Pool Sweep", " Outdoor Pool"],
      },
    ],
    greenFeatures: ["solar"],
    text: "WOW! Look at this fabulous price! Stunning 3 bed+ Office, 2.5 bath home tucked away on a beautiful tree-lined street in South Livermore. Newly remodeled throughout featuring a beautiful kitchen with quartz counters, white shaker cabinetry, and stainless steel appliances, refinished hardwood flooring throughout, and extensive recessed lighting in the living, kitchen and family rooms. All new dual paned windows, including a new slider in the primary bedroom. New interior and exterior painting, all newly remodeled bathrooms with shaker cabinets, porcelain tile floors, and Quartz counters. Primary bath includes a soaking tub, separate shower, and wall safe. Additional amenities include new washer and dryer, New garage door and opener and New heat pump water heater for main portion of home. There is a separate water heater for the primary bath. The large lot boasts over 9300sf and includes a newly Refinished pool including new tile & plaster, new plumbing for the remote filter and pump, all new concrete decking and drainage system, updated landscaping with water conserving drip system, possible sya, and a raised redwood deck accessing the living room and kitchen. Solar owned with inverter. Located within walking distance to downtown, shops and restaurants, Arroyo trails, and more!",
  },
  {
    img: "http://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41071543/0/0/0/c7a1d6c778a7297d4729e8842e3c9717/136/c6ce7e08fc01d61cdcdc27e2e73a8005/41071543-61da6702-10e7-4e46-978c-7fc4417dc627.JPG",
    price: 1199000,
    area: 1809,
    beds: 3,
    baths: 2,
    location: "livermore",
    type: "residential",
    built: 1968,
    address: "1581 Vancouver Way Livermore CA, 94550",
    interior: [
      {
        stories: 1,
        bedrooms: 3,
        totalBathrooms: 2,
        fullBathrooms: 2,
        interiorFeatures: [
          "Dining Area",
          "Family Room",
          "Breakfast Bar",
          "Laminate Counters",
          "Pantry",
        ],
        appliances: [
          "Dishwasher",
          "Double Oven",
          "Electric Range",
          "Grill Built-in",
          "Microwave",
          "Range",
        ],
        laundryDescription: "Laundry Room",
        floorDescription: "Tile, Vinyl, Carpet",
        fireplace: true,
        fireplaceDescription: "Family Room",
        cooling: true,
        coolingDescription: "central air",
        heating: true,
        heatingDescription: "forced air",
      },
    ],
    exterior: [
      {
        lotSize: 0.16,
        exteriorFeatures: ["Back Yard", "Front Yard"],
        lotFeatures: ["regular"],
        architechturalStyle: "Contemporary",
        roof: "Composition Shingles",
        sewer: "public sewer",
      },
    ],

    otherDetails: [
      {
        garage: true,
        garageSpaces: 2,
        parking: ["Attached"],
        parkingTotal: 2,
        view: false,
        county: "alameda",
        waterSource: "public",
        pool: false,
        poolFeatures: ["none"],
      },
    ],

    text: "Open House Sunday 1:00-4:00pm. Discover this delightful 3BR/2BA, 1,809 sq ft single-story home in the highly sought-after, desirable South Livermore community of Sunset East. Unique features like a one-of-a-kind kitchen-in-the-round with built-in BBQ set this property apart, while the original double front doors and art deco solid brass hardware make a striking first impression. Expansive windows bathe the home in light, creating a warm, inviting atmosphere. Set on a generous 7,000 sq ft lot, this property offers ample space for outdoor living, including a patio perfect for dining al fresco, lush greenery for relaxation, and plenty of room to enjoy the serene surroundings or play on the putting green or shuffleboard court. The attached two-car garage provides ample storage and parking. along with 2 large sheds on the side yard. Priced with room for your vision, this property offers outstanding value for buyers looking to customize. Located in a prime Livermore location, this home is within close proximity to top-rated schools, parks, shopping, and dining. Enjoy the best of Livermore living with easy access to local wineries, hiking trails, fishing, award-winning golf courses, and the vibrant downtown area. Great investment opportunity!",
  },
  {
    img: "http://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41072005/0/0/0/ae4a67e528917ad219b4a6138c416e2f/136/d7d4fdbaeb4a9ab43d4bf01ed6ab660e/41072005-3119485c-45c8-4de8-b25e-f49bcce116c8.JPG",
    price: 1799000,
    area: 3137,
    beds: 6,
    baths: 3,
    location: "livermore",
    type: "residential",
    built: 2000,
    address: "2247 Bluffs Ct Livermore CA, 94551",
    interior: [
      {
        stories: 2,
        bedrooms: 6,
        totalBathrooms: 3,
        fullBathrooms: 3,
        interiorFeatures: [
          "Bonus/Plus Room",
          "Stone Counters",
          "Kitchen Island",
          "Updated Kitchen",
        ],
        appliances: [
          "Disposal",
          "Gas Range",
          "Microwave",
          "Refrigerator",
          "Gas Water Heater",
        ],
        laundryDescription: "Laundry Room",
        floorDescription: "Carpet, Tile, Vinyl",
        fireplace: true,
        fireplaceDescription: "Family Room",
        cooling: true,
        coolingDescription: "Ceiling Fan(s), Zoned",
        heating: true,
        heatingDescription: "zoned",
      },
    ],
    exterior: [
      {
        lotSize: 0.29,
        exteriorFeatures: ["Back Yard", "Front Yard", "Sprinklers Automatic"],
        lotFeatures: ["court", "premium lot"],
        architechturalStyle: "Contemporary",

        sewer: "public sewer",
      },
    ],
    schoolInformation: [{ schoolDistrict: "Livermore Valley (925) 606-3200" }],
    otherDetails: [
      {
        garage: true,
        garageSpaces: 1,
        parking: ["Attached", "Garage Door Opener"],
        parkingTotal: 1,
        view: false,
        county: "alameda",
        waterSource: "public",
        pool: true,
        poolFeatures: [
          "Gas Heat",
          "In Ground",
          "Solar Heat",
          "Solar Pool Owned",
        ],
      },
    ],

    text: "Must see this stunning home in the highly desirable 'Bluffs' community surrounded by open space and hills. From the moment you drive up you will appreciate the premium end of court location and oversized estate lot. The double WEST facing front doors welcome you into the light and bright interior with upgraded plank and tile flooring. The functional floor plan features ONE FULL BEDROOM AND BATH DOWNSTAIRS and an OVERSIZED BONUS ROOM or possible 6th bedroom. Spacious chef style kitchen features large island with seating and sink, slab stone counters, gas range, double ovens, and abundant cabinetry with built-in desk area. Luxurious primary suite with bay window, plush neutral carpet and ceiling fan. The en-suite bath has a separate tub and walk-in shower with new seamless shower enclosure, double sinks, and separate vanity. Backyard is ready for entertaining with a fully gated in-ground pool and spa with pool SOLAR, gas fire pit, large grassy area, mature trees and side yard with storage shed and fruit trees. NO REAR NEIGHBORS!",
  },
  {
    img: "http://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41072759/0/0/0/03551d20de6a866c67360a77c82f88c7/136/692d6d501f4dda182be2f827ea08d0c2/41072759-eaea08c2-a009-4258-9922-2bd4687834d6.JPG",
    price: 1189000,
    area: 1427,
    beds: 3,
    baths: 2,
    location: "livermore",
    type: "residential",
    built: 1970,
    address: "728 Yolo Way Livermore CA, 94551",
    interior: [
      {
        stories: 1,
        bedrooms: 3,
        totalBathrooms: 2,
        fullBathrooms: 2,
        interiorFeatures: ["Dining Area", "Family Room", "Updated Kitchen"],
        appliances: ["Dishwasher", "Microwave", "Gas Water Heater"],
        laundryDescription: "Hookups Only",
        floorDescription: "Laminate",
        fireplace: true,
        fireplaceDescription: "family room",
        cooling: false,
        coolingDescription: "No",
        heating: true,
        heatingDescription: "forced air",
      },
    ],
    exterior: [
      {
        lotSize: 0.23,
        exteriorFeatures: ["Back Yard", "Front Yard"],
        lotFeatures: ["corner lot", "premium lot"],
        architechturalStyle: "ranch",
        roof: "shingle",
        sewer: "public sewer",
      },
    ],

    otherDetails: [
      {
        garage: true,
        garageSpaces: 2,
        parking: ["Attached"],
        parkingTotal: 2,
        view: false,
        county: "alameda",
        waterSource: "public",
        pool: true,
        poolFeatures: ["above ground"],
      },
    ],

    text: "Welcome to 728 Yolo Way! This picture-perfect, single-story, single-family home is located in the highly desirable Somerset neighborhood. It sits on an oversized lot, which offers the possibility of having dual side-yard access or significantly expanding the backyard. The home features three bedrooms, two full baths, and a formal living room, as well as a family room. Recent updates and improvements include updated kitchen and baths, updated baseboards, doors and casings, a finished garage, new with epoxy floors, newer roof, solar system and much more. Venture outside to enjoy a large yard, covered back patio, new lawn, and above-ground pool for those warm summer days! Or consider your own working farm! The current owners have enjoyed the covered patio as outdoor living 9 out of the 12 months of the year as it is a great place to relax and enjoy the fresh air. This property is just around the corner from the Henry R. Maitland Park, minutes from miles of biking and hiking trails, and just a short drive to Livermore's award-winning downtown, wine country, shopping, entertainment, and schools.",
  },
  {
    img: "http://cdnparap30.paragonrels.com/ParagonImages/Property/P3/MAXEBRDI/41072444/0/0/0/e9a807118753bb7a1b4073077d34ce65/136/a3d8195609b4d50c937704c382b57814/41072444-ba403fce-bfd0-4954-b9e3-d4180edb29a4.JPG",
    price: 1650000,
    area: 2303,
    beds: 5,
    baths: 3,
    location: "livermore",
    type: "residential",
    built: 1998,
    address: "6460 Owl Way Livermore CA, 94551",
    interior: [
      {
        stories: 2,
        bedrooms: 5,
        totalBathrooms: 3,
        fullBathrooms: 2,
        interiorFeatures: [
          "Kitchen/Family Combo",
          "Breakfast Bar",
          "Stone Counters",
          "Eat-in Kitchen",
          "Updated Kitchen",
          "Smart Thermostat",
        ],
        appliances: [
          "Dishwasher",
          "Disposal",
          "Gas Range",
          "Plumbed For Ice Maker",
          "Microwave",
          "Washer",
          "Gas Water Heater",
          "Tankless Water Heater",
        ],
        laundryDescription:
          "220 Volt Outlet, Dryer, Gas Dryer Hookup, Laundry Room, Washer, Cabinets, Washer/Dryer Stacked Incl",
        floorDescription: "Hardwood",
        fireplace: true,
        fireplaceDescription: "Stone, Wood Burning",
        cooling: true,
        coolingDescription: "Ceiling Fan(s), Zoned",
        heating: true,
        heatingDescription: "zoned",
      },
    ],
    exterior: [
      {
        lotSize: 0.17,
        exteriorFeatures: [
          "Back Yard",
          "Front Yard",
          "Sprinklers Front",
          "Landscape Back",
          "Landscape Front",
          "Low Maintenance",
        ],
        lotFeatures: ["regular"],
        architechturalStyle: "Contemporary",
        roof: "tile",
        sewer: "public sewer",
      },
    ],
    schoolInformation: [{ schoolDistrict: "Livermore Valley (925) 606-3200" }],
    otherDetails: [
      {
        garage: true,
        garageSpaces: 2,
        parking: [
          "Attached",
          "Electric Vehicle Charging Station(s)",
          "Garage Door Opener",
        ],
        parkingTotal: 2,
        view: false,
        county: "alameda",
        waterSource: "public",
        pool: true,
        poolFeatures: [
          "In Ground",
          "Pool Sweep",
          "Solar Heat",
          "Spa",
          "Pool/Spa Combo",
          "Solar Pool Owned",
          "Outdoor Pool",
        ],
      },
    ],

    text: `This amazing home is truly resort style living at its finest! Original owner
home that shows pride of ownership throughout. This home is an entertainers
dream home with a gorgeous saltwater pool w/raised spa including water features
& solar heating, outdoor BBQ w/stubbed gas line. Stunning Hickory hardwood
flooring throughout most of the home w/6.5" baseboards! Gourmet kitchen with
shaker cabinets,granite counters, custom tile backsplash, drop lights, on demand
hot water, SS stove/oven new in 2024, wine refrigerator & reverse osmosis!
Primary bath remodel w/barn door, walk in shower, custom tile work, quartz
counter & lighted mirrors! Upgrades to all bathrooms. Crown molding in all
bedrooms, bathrooms, kitchen & family room. French doors lead you to your
outdoor oasis. Large laundry room w/expanded cabinetry. Home office installation
in loft. Solar for the home, Tesla charger, High End Lenox AC system, New HVAC
system & Nest thermostats installed for dual zone system in 2023! New attic
insulation in 2023. Closet organizers in all bedrooms. Garage Epoxy floor,
Storage cabinets, water purifier, tankless water heater & new garage door
opener. Drought tolerant front yard with artificial lawn & new irrigation
controlled by phone app. Close to Schools, park, wine country, & HWYs 580/84`,
  },
  // Pleasanton
];
